### ISSUE TITLE
Consider using pip-tools to create requirements

### ISSUE THREAD

**Issue by offbyone** [quakkels/rssdiscoveryengine#18]
Right now requirements_dev.txt is super locked in. It might be worth creating a `requirements_dev.in` that just specifies the dependency boundaries you need, and regenerate `requirements_dev.txt` when you lock them in for deployment.

https://github.com/jazzband/pip-tools

(Not my project, but I'm a big fan. Some more info [here](https://hynek.me/articles/python-app-deps-2018/) and also how I use it with direnv [here](https://ideas.offby1.net/posts/direnv-and-pip-tools-together.html))

**Comment by quakkels** [comment]
Thank you for recommending this. I've used pipenv before (mentioned in the article you linked) for some other small projects, and I didn't know about the issues people have encountered with it.

I'll play around with pip-tools for a bit. It might be a good for RSS Discovery Engine.
